# Generated by Django 5.2 on 2025-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_camera_period_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(help_text='URL of the camera main-stream, ex. rtsp://admin:examplepass123!@192.168.1.100:554/Streaming/Channels/101/', max_length=255),
        ),
    ]
