# Generated by Django 5.2 on 2025-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekdays', models.CharField(help_text='e.g. Mon,Tue,Wed', max_length=20)),
            ],
        ),
    ]
