# Generated by Django 5.2 on 2025-04-22 16:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_recognitionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionschedule',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=27),
        ),
    ]
