# Generated by Django 5.2 on 2025-04-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_recognitionschedule_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionschedule',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.camera'),
        ),
    ]
