# Generated by Django 5.2 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_recognitionschedule_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionschedule',
            name='camera',
        ),
        migrations.AddField(
            model_name='recognitionschedule',
            name='camera',
            field=models.ManyToManyField(related_name='schedules', to='attendance.camera'),
        ),
    ]
