# Generated by Django 5.2 on 2025-04-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_recognitionschedule_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recognitionschedule',
            old_name='camera',
            new_name='cameras',
        ),
    ]
