# Generated by Django 5.2 on 2025-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_camera_recognitionschedule_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='score',
            field=models.FloatField(blank=True, help_text='Cosine similarity score of the recognition match.', null=True),
        ),
    ]
