# Generated by Django 5.2 on 2025-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancelog_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='score',
            new_name='match_score',
        ),
    ]
