# Generated by Django 5.2 on 2025-04-25 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_score_attendancelog_match_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 25)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('student', 'period', 'date')},
        ),
    ]
