# Generated by Django 5.2 on 2025-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_attendancelog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='attendance_window_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Time window in seconds to update attendance if a better match is found. Default is 15 seconds.'),
        ),
    ]
