# Generated by Django 5.2 on 2025-04-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_period_attendance_window_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
