# Generated by Django 5.2 on 2025-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_camera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='cropped_face',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_crops/'),
        ),
    ]
