# Generated by Django 5.2 on 2025-05-11 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_attendancelog_cropped_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
